# -*- coding: utf-8 -*-
"""TrilhaEPR_SAD(v4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvRblicz_YJWt4qZ5XGsncmCBSJYipVj
"""

import streamlit as st
import pandas as pd
from sentence_transformers import SentenceTransformer, util
import re

# ==========================================
# 1. CONFIGURAÇÃO E IA (Cache)
# ==========================================
st.set_page_config(page_title="SAD V4 - Eng. Produção UnB", page_icon="🚀", layout="wide")

@st.cache_resource
def carregar_ia():
    return SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

modelo_ia = carregar_ia()

@st.cache_data
def carregar_base():
    # Carrega a base consolidada
    df = pd.read_csv('disciplinas.csv')

    # 1. Limpeza de espaços e padronização para maiúsculas
    df['Codigo'] = df['Codigo'].astype(str).str.strip().str.upper()

    # 2. TRATAMENTO DE DUPLICATAS: Garante que cada Código seja único
    # Agrupa e resolve conflitos: une horários e pega o maior crédito
    df = df.groupby('Codigo').agg({
        'Nome': 'first',
        'Tipo': 'first',
        'Pre_Requisitos': 'first',
        'Correquisitos': 'first',
        'Equivalencias': 'first',
        'Horario': lambda x: ', '.join(set(filter(None, x.astype(str).str.replace('nan', '')))),
        'Credito': 'max',
        'Ementa': 'first'
    }).reset_index()

    # 3. Tratamento de tipos e preenchimento de vazios
    df['Credito'] = pd.to_numeric(df['Credito'], errors='coerce').fillna(0).astype(int)
    colunas_texto = ['Nome', 'Tipo', 'Pre_Requisitos', 'Correquisitos', 'Equivalencias', 'Horario', 'Ementa']
    df[colunas_texto] = df[colunas_texto].fillna('')

    # 4. Vetorização para IA de Carreira (Apenas Optativas)
    def gerar_vetor(row):
        if row['Tipo'] == 'OPT' and len(str(row['Ementa'])) > 10:
            return modelo_ia.encode(str(row['Ementa']))
        return None

    df['Vetor_Ementa'] = df.apply(gerar_vetor, axis=1)
    return df

# ==========================================
# 2. MOTOR DE LOGICA CURRICULAR
# ==========================================
class MotorSAD:
    def __init__(self, df):
        self.df = df
        self.disciplinas = self.df.set_index('Codigo').to_dict('index')

    def extrair_slots(self, horario):
        if not horario or 'Não Ofertada' in horario: return []
        slots = []
        for h_turma in str(horario).split(','):
            match = re.search(r'([2-7]+)([MTN])([1-7]+)', h_turma.strip())
            if match:
                dias, turno, horas = match.groups()
                for d in dias:
                    for h in horas:
                        slots.append((d, turno, h))
        return slots

    def checar_requisitos(self, expressao, historico):
        if not expressao or expressao.strip() == '': return True
        exp = str(expressao).replace(',', ' E ').replace('OU', ' or ').replace('E', ' and ')
        codigos = set(re.findall(r'[A-Z]{3}\d{4}', exp))
        for cod in codigos:
            # Considera cumprido se estiver no histórico
            exp = re.sub(rf'\b{cod}\b', str(cod in historico), exp)
        try: return eval(exp)
        except: return False

    def calcular_score(self, codigo, objetivo_vetor):
        dados = self.disciplinas[codigo]
        score = 0
        # Peso Carreira (IA)
        if dados['Vetor_Ementa'] is not None:
            sim = util.cos_sim(objetivo_vetor, dados['Vetor_Ementa']).item()
            score += (sim * 40)
        # Peso Noturno
        if 'N' in str(dados['Horario']): score += 30
        # Peso Obrigatória (Caminho Crítico)
        if dados['Tipo'] == 'OBRIG': score += 30
        return round(max(0, score), 1)

# ==========================================
# 3. INTERFACE STREAMLIT
# ==========================================
st.title("🎒 SAD Engenharia de Produção - V4")
st.markdown("Otimização de grade horária baseada em histórico real e preferência noturna.")

df_base = carregar_base()
motor = MotorSAD(df_base)

descricoes_areas = {
    "Eng. de Operações": "Sistemas de produção, manufatura, controle de processos e PCP.",
    "Logística": "Cadeia de suprimentos, transporte, estoques e modais.",
    "Pesquisa Operacional/Dados": "Modelagem matemática, otimização e análise de dados.",
    "Gestão e Economia": "Finanças, viabilidade econômica e gestão de projetos."
}

# SIDEBAR
st.sidebar.header("👤 Histórico e Preferências")
historico_raw = st.sidebar.text_area("Códigos das matérias feitas (separados por vírgula):", placeholder="Ex: MAT0025, EPR0056")
historico = [c.strip().upper() for c in historico_raw.split(',') if c.strip()]

trilha = st.sidebar.selectbox("Trilha de Carreira:", list(descricoes_areas.keys()))
carga_max = st.sidebar.slider("Limite de Horas Semestral:", 60, 420, 240, 30)

if st.sidebar.button("🚀 Otimizar Matrícula", type="primary"):
    vetor_foco = modelo_ia.encode(descricoes_areas[trilha])

    # 1. Filtro de Possibilidades
    possiveis = []
    for cod, dados in motor.disciplinas.items():
        if cod not in historico:
            if motor.checar_requisitos(dados['Pre_Requisitos'], historico):
                if dados['Horario'] and 'Não Ofertada' not in dados['Horario']:
                    score = motor.calcular_score(cod, vetor_foco)
                    possiveis.append({'Codigo': cod, 'Score': score, 'Dados': dados})

    # 2. Ordenação por Score (IA + Noite + Obrigatória)
    possiveis = sorted(possiveis, key=lambda x: x['Score'], reverse=True)

    # 3. Mochila com Conflito de Horário
    grade, slots, total_h = [], [], 0
    for item in possiveis:
        c = item['Dados']['Credito']
        if total_h + c <= carga_max:
            slots_materia = motor.extrair_slots(item['Dados']['Horario'])
            if not any(s in slots for s in slots_materia):
                grade.append(item)
                slots.extend(slots_materia)
                total_h += c

    # 4. Resultados
    if not grade:
        st.warning("Nenhuma disciplina encontrada para os critérios selecionados.")
    else:
        st.subheader(f"📊 Sugestão de Matrícula ({total_h}h Sugeridas)")
        for m in grade:
            with st.expander(f"**{m['Codigo']} - {m['Dados']['Nome']}** (Score: {m['Score']})"):
                st.write(f"🕒 **Horário:** {m['Dados']['Horario']} | ⚖️ **Carga:** {m['Dados']['Credito']}h")
                st.write(f"📖 **Ementa:** {m['Dados']['Ementa']}")