# -*- coding: utf-8 -*-
"""TrilhaEPR_SAD(v3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kwY5r75675iw6yiW8klHj1MHdLdv5tY

---
"""

import streamlit as st
import pandas as pd
from sentence_transformers import SentenceTransformer, util
import re

# ==========================================
# 1. CONFIGURAÇÃO DA PÁGINA
# ==========================================
st.set_page_config(page_title="SAD - Engenharia de Produção", page_icon="🎒", layout="wide")
st.title("🎒 Sistema de Apoio à Decisão: Otimização de Matrícula")
st.markdown("Encontre as melhores disciplinas optativas baseadas no seu perfil e disponibilidade de tempo, utilizando Inteligência Artificial.")

# ==========================================
# 2. CARREGAMENTO DO CÉREBRO DA IA (Com Cache)
# ==========================================
# O cache impede que a IA seja baixada toda vez que o aluno apertar o botão
@st.cache_resource
def carregar_ia():
    return SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

modelo_ia = carregar_ia()

# ==========================================
# 3. DICIONÁRIO E VETORIZAÇÃO (Com Cache)
# ==========================================
descricoes_areas = {
    "Eng. de Operações e Processos": "Sistemas de produção, manufatura, controle de chão de fábrica, layout e PCP.",
    "Logística": "Gestão da cadeia de suprimentos, transporte, modais, estoque e armazenagem física.",
    "Pesquisa Operacional": "Otimização combinatória, simulação de processos, modelos matemáticos e estatística.",
    "Eng. da Qualidade": "Gestão da qualidade, controle estatístico, metrologia, confiabilidade, seis sigma e melhoria contínua.",
    "Eng. do Produto": "Desenvolvimento de produtos, inovação, ciclo de vida, design, prototipagem e patentes.",
    "Eng. Organizacional": "Gestão estratégica, sistemas de informação, gestão de projetos, empreendedorismo e recursos humanos.",
    "Eng. Econômica": "Matemática financeira, análise de investimentos, controle de custos, mercados e viabilidade econômica.",
    "Eng. do Trabalho": "Ergonomia, segurança do trabalho, saúde ocupacional, biomecânica e prevenção de acidentes.",
    "Eng. da Sustentabilidade": "Sustentabilidade ambiental, ecologia, gestão de resíduos, recursos naturais e ESG.",
    "Tecnologia e Automação (Apoio)": "Programação de computadores, algoritmos, banco de dados, circuitos elétricos e automação industrial.",
    "Negócios e Humanidades (Apoio)": "Administração, psicologia aplicada, direito, sociologia, marketing e comportamento organizacional."
}

@st.cache_data
def carregar_dados():
    # Caminho relativo: Ele vai procurar o CSV na mesma pasta do GitHub
    df_optativas = pd.read_csv('Optativas_EPR.csv')

    # Extrai as horas (Regex)
    def extrair_horas(texto):
        match = re.search(r'(\d+)h', str(texto).lower())
        return int(match.group(1)) if match else 60

    df_optativas['Horas'] = df_optativas['Nome'].apply(extrair_horas)
    df_optativas['Nome_Limpo'] = df_optativas['Nome'].apply(lambda x: str(x).split('-')[0].strip())

    # Vetoriza as ementas (Roda só uma vez quando o site liga)
    def gerar_vetor(ementa):
        if pd.isna(ementa) or "ATIVIDADE COMPLEMENTAR" in str(ementa).upper() or len(str(ementa)) < 10:
            return None
        return modelo_ia.encode(str(ementa))

    df_optativas['Vetor_Ementa'] = df_optativas['Ementa'].apply(gerar_vetor)
    return df_optativas

df_optativas = carregar_dados()

# Vetoriza os objetivos da ABEPRO
vetores_objetivos = {area: modelo_ia.encode(desc) for area, desc in descricoes_areas.items()}

# ==========================================
# 4. FUNÇÃO DE MATEMÁTICA RÁPIDA (O Motor)
# ==========================================
def calcular_similaridade_rapida(vetor_ementa, objetivo):
    if vetor_ementa is None: return 0.0
    vetor_obj = vetores_objetivos[objetivo]
    similaridade = util.cos_sim(vetor_obj, vetor_ementa).item()
    nota_final = max(0, similaridade * 100)

    # Nota de corte mantida em 50 para não esvaziar a mochila
    return round(nota_final, 1) if nota_final >= 50 else 0.0

# ==========================================
# 5. A INTERFACE DO USUÁRIO (Sidebar)
# ==========================================
st.sidebar.header("⚙️ Configurações do Semestre")

objetivo_selecionado = st.sidebar.selectbox("🎯 Qual sua Trilha de Carreira?", list(descricoes_areas.keys()))
carga_maxima = st.sidebar.slider("⏳ Carga Máxima Suportada (Noturno):", min_value=60, max_value=420, value=240, step=30)
horas_obrigatorias = st.sidebar.slider("📚 Horas de Obrigatórias Simuladas:", min_value=0, max_value=420, value=120, step=30)

botao_gerar = st.sidebar.button("🚀 Gerar Grade Otimizada", type="primary", use_container_width=True)

# ==========================================
# 6. O PROCESSAMENTO (Ao Clicar no Botão)
# ==========================================
if botao_gerar:
    capacidade_mochila = carga_maxima - horas_obrigatorias

    # Cards visuais da capacidade
    col1, col2, col3 = st.columns(3)
    col1.metric("Carga Máxima", f"{carga_maxima}h")
    col2.metric("Obrigatórias", f"{horas_obrigatorias}h")
    col3.metric("Espaço Livre", f"{capacidade_mochila}h", delta=f"{capacidade_mochila}h livres", delta_color="normal")

    st.divider()

    if capacidade_mochila <= 0:
        st.error("⚠️ Você já atingiu ou ultrapassou sua capacidade máxima. O sistema não recomenda adicionar optativas neste semestre.")
    else:
        # Aplica a matemática vetorial
        df_optativas['Pontuacao_Match'] = df_optativas['Vetor_Ementa'].apply(
            lambda v: calcular_similaridade_rapida(v, objetivo_selecionado)
        )

        if df_optativas['Pontuacao_Match'].sum() == 0:
            st.warning(f"❌ Nenhuma optativa possui ligação semântica com a área de '{objetivo_selecionado}'.")
        else:
            df_rankeado = df_optativas.sort_values(by='Pontuacao_Match', ascending=False).reset_index(drop=True)

            horas_acumuladas = 0

            st.subheader(f"💡 Sugestão Otimizada para: {objetivo_selecionado}")

            for index, row in df_rankeado.iterrows():
                if row['Pontuacao_Match'] == 0: continue

                # Regra do Problema da Mochila
                if (horas_acumuladas + row['Horas']) <= capacidade_mochila:
                    horas_acumuladas += row['Horas']

                    nota = row['Pontuacao_Match']
                    if nota >= 70:
                        tag = "🎯 Alta Aderência (Foco Principal)"
                    elif nota >= 60:
                        tag = "🟢 Boa Opção (Área de Interesse)"
                    else:
                        tag = "🟡 Opção Correlata (Plano B / Exatas ou Humanas Gerais)"

                    # Imprime a recomendação em caixas de sucesso na tela
                    st.success(f"**{row['Nome_Limpo']}** ({row['Horas']}h)  \n"
                               f"Score Semântico: **{nota}%** | *{tag}*")

            st.info(f"**Resumo da Mochila:** O sistema selecionou matérias preenchendo **{horas_acumuladas}h** do seu tempo livre disponível.")

