# -*- coding: utf-8 -*-
"""TrilhaEPR_SAD(v4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvRblicz_YJWt4qZ5XGsncmCBSJYipVj

---
"""

import streamlit as st
import pandas as pd
from sentence_transformers import SentenceTransformer, util
import re

# ==========================================
# 1. CONFIGURAÇÃO E IA (Cache)
# ==========================================
st.set_page_config(page_title="SAD V4 - Eng. Produção UnB", page_icon="🚀", layout="wide")

@st.cache_resource
def carregar_ia():
    return SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

modelo_ia = carregar_ia()

# ==========================================
# 2. MOTOR DE LOGICA CURRICULAR (Back-end)
# ==========================================
class MotorSAD:
    def __init__(self, df):
        self.df = df.fillna('')
        self.disciplinas = self.df.set_index('Codigo').to_dict('index')

    def extrair_slots(self, horario):
        if not horario or horario == 'Não Ofertada': return []
        # Suporta múltiplas turmas separadas por vírgula
        todos_slots = []
        for h_turma in str(horario).split(','):
            match = re.search(r'([2-7]+)([MTN])([1-7]+)', h_turma.strip())
            if match:
                dias, turno, horas = match.groups()
                for d in dias:
                    for h in horas:
                        todos_slots.append((d, turno, h))
        return todos_slots

    def checar_requisitos(self, expressao, historico):
        if not expressao: return True
        exp = str(expressao).replace(',', ' E ').replace('OU', 'or').replace('E', 'and')
        codigos = set(re.findall(r'[A-Z]{3}\d{4}', exp))
        for cod in codigos:
            # Checa se o aluno fez a matéria ou alguma equivalente
            status = cod in historico
            exp = re.sub(rf'\b{cod}\b', str(status), exp)
        try: return eval(exp)
        except: return False

# ==========================================
# 3. CARREGAMENTO DOS DADOS (Super CSV)
# ==========================================
@st.cache_data
def carregar_base():
    # O arquivo que consolidamos com Horarios e Créditos limpos
    df = pd.read_csv('base_disciplinas_2026.csv')
    # Vetorização apenas para Optativas (IA de Carreira)
    def vetorizar(row):
        if row['Tipo'] == 'OPT' and len(str(row['Ementa'])) > 10:
            return modelo_ia.encode(str(row['Ementa']))
        return None
    df['Vetor'] = df.apply(vetorizar, axis=1)
    return df

df_base = carregar_base()
motor = MotorSAD(df_base)

# ==========================================
# 4. INTERFACE DO USUÁRIO
# ==========================================
st.sidebar.header("👤 Perfil do Aluno")
historico_raw = st.sidebar.text_area("Matérias Concluídas (Códigos):",
                                    placeholder="Ex: MAT0025, IFD0171, EPR0056")
historico_usuario = [c.strip().upper() for c in historico_raw.split(',') if c.strip()]

st.sidebar.divider()
st.sidebar.header("⚙️ Preferências 2026.1")
area_foco = st.sidebar.selectbox("Trilha de Carreira:", ["Eng. de Operações", "Logística", "Econômica", "Dados"])
carga_max = st.sidebar.slider("Carga Horária Máxima (h):", 60, 420, 240, 30)

if st.sidebar.button("🚀 Gerar Grade Otimizada", type="primary"):
    # --- PROCESSO DE FILTRAGEM ---
    possiveis = []
    for cod, dados in motor.disciplinas.items():
        if cod not in historico_usuario:
            if motor.checar_requisitos(dados['Pre_Requisitos'], historico_usuario):
                if dados['Horario'] != 'Não Ofertada':
                    possiveis.append(cod)

    # --- SCORE FINAL (Mochila V4) ---
    # Prioridade = Noturno (30%) + Carreira (40%) + Caminho Crítico (30%)
    recomendacoes = []
    for cod in possiveis:
        dados = motor.disciplinas[cod]
        score = 0
        if 'N' in str(dados['Horario']): score += 30 # Peso Noturno
        # Aqui entrariam os outros cálculos de IA e Caminho Crítico
        recomendacoes.append({'Codigo': cod, 'Score': score, 'Dados': dados})

    recomendacoes = sorted(recomendacoes, key=lambda x: x['Score'], reverse=True)

    # --- MONTAGEM DA GRADE (Evitando Conflito) ---
    grade_final = []
    slots_ocupados = []
    horas_acumuladas = 0

    for item in recomendacoes:
        horario = item['Dados']['Horario']
        credito = int(item['Dados']['Credito'])

        if horas_acumuladas + credito <= carga_max:
            if not any(slot in slots_ocupados for slot in motor.extrair_slots(horario)):
                grade_final.append(item)
                slots_ocupados.extend(motor.extrair_slots(horario))
                horas_acumuladas += credito

    # --- DISPLAY ---
    st.subheader(f"✅ Grade Sugerida para 2026.1 ({horas_acumuladas}h)")
    for item in grade_final:
        with st.expander(f"**{item['Codigo']} - {item['Dados']['Nome']}**"):
            st.write(f"🕒 **Horário:** {item['Dados']['Horario']} | 🎓 **Créditos:** {item['Dados']['Credito']}h")
            st.write(f"📖 **Ementa:** {item['Dados']['Ementa'][:200]}...")

import pandas as pd
import re

class MotorCurricular:
    def __init__(self, caminho_csv):
        """
        Inicializa o motor carregando o Super CSV e limpando os dados.
        """
        # 1. Carrega o banco de dados
        self.df = pd.read_csv(caminho_csv)

        # 2. Tratamento de nulos (substitui NaN por strings vazias para evitar erros)
        self.df.fillna('', inplace=True)

        # 3. Garante que os créditos sejam números inteiros
        self.df['Credito'] = pd.to_numeric(self.df['Credito'], errors='coerce').fillna(0).astype(int)

        # 4. Cria um dicionário rápido para buscar dados de uma matéria específica
        self.disciplinas = self.df.set_index('Codigo').to_dict('index')
        print(f"✅ Base carregada com sucesso: {len(self.df)} disciplinas prontas para análise.")

    def checar_equivalencia(self, codigo_alvo, historico_aluno):
        """
        Verifica se o aluno fez a matéria OU alguma de suas equivalências.
        """
        if codigo_alvo in historico_aluno:
            return True

        equivalencias_raw = self.disciplinas.get(codigo_alvo, {}).get('Equivalencias', '')
        if equivalencias_raw:
            # Extrai todos os códigos da string de equivalência
            codigos_equiv = re.findall(r'[A-Z]{3}\d{4}', str(equivalencias_raw))
            # Se a interseção entre as equivalências e o histórico for maior que 0, o aluno cumpriu!
            if set(codigos_equiv).intersection(set(historico_aluno)):
                return True

        return False

    def avaliar_pre_requisitos(self, expressao_raw, historico_aluno):
        """
        O "Parser" que traduz a lógica complexa do SIGAA para Python.
        """
        if not expressao_raw or str(expressao_raw).strip() == "":
            return True # Sem pré-requisitos = Liberado

        expressao = str(expressao_raw)

        # Padroniza a sintaxe: troca vírgulas por " E " e ajusta os conectivos
        expressao = expressao.replace(',', ' E ')
        expressao = expressao.replace('OU', 'or').replace('E', 'and')

        # Encontra todos os códigos (ex: MAT0025) na expressão
        codigos_na_expressao = set(re.findall(r'[A-Z]{3}\d{4}', expressao))

        # Avalia código por código
        for codigo in codigos_na_expressao:
            # Usa a nossa função inteligente que já checa as equivalências!
            if self.checar_equivalencia(codigo, historico_aluno):
                expressao = re.sub(rf'\b{codigo}\b', 'True', expressao)
            else:
                expressao = re.sub(rf'\b{codigo}\b', 'False', expressao)

        # Resolve a matemática booleana
        try:
            return eval(expressao)
        except Exception as e:
            print(f"⚠️ Erro ao avaliar expressão: {expressao_raw} -> {e}")
            return False

# ==========================================
# TESTANDO O MOTOR
# ==========================================
if __name__ == "__main__":
    # Instancia a classe apontando para o seu arquivo
    # sad = MotorCurricular('seu_super_csv_final.csv')
    pass

def calcular_aderencia_noturna(self, codigo):
        """
        Analisa o código de horário (ex: 24N12) e retorna um score de 0 a 100.
        """
        horario_raw = self.disciplinas.get(codigo, {}).get('Horario', '').upper()

        if not horario_raw:
            return 0

        # Se houver oferta à NOITE (N), ganha prioridade máxima
        if 'N' in horario_raw:
            return 100
        # Se for à TARDE (T), tem aderência parcial
        elif 'T' in horario_raw:
            return 30
        # MANHÃ (M) tem aderência mínima para este perfil
        return 0

    def filtrar_por_periodo(self, lista_possiveis, apenas_noite=False):
        """
        Ordena as matérias disponíveis priorizando as que têm oferta noturna.
        """
        materias_ordenadas = sorted(
            lista_possiveis,
            key=lambda c: self.calcular_aderencia_noturna(c),
            reverse=True
        )

        if apenas_noite:
            return [c for c in materias_ordenadas if self.calcular_aderencia_noturna(c) > 50]

        return materias_ordenadas

def extrair_slots(self, horario_raw):
        """
        Converte '24N12' em [('2', 'N', '1'), ('2', 'N', '2'), ('4', 'N', '1'), ('4', 'N', '2')]
        """
        if not horario_raw or horario_raw == 'Não Ofertada':
            return []

        # Regex para separar os componentes: Dias | Turno | Horas
        # Exemplo: '246T12' -> Dias: 246, Turno: T, Horas: 12
        match = re.match(r'([2-7]+)([MTN])([1-7]+)', horario_raw.strip())
        if not match:
            return []

        dias, turno, horas = match.groups()
        slots = []
        for d in dias:
            for h in horas:
                slots.append((d, turno, h))
        return slots

    def tem_conflito(self, horario_novo, slots_ocupados):
        """
        Verifica se a nova matéria bate com alguma já escolhida.
        """
        slots_novos = self.extrair_slots(horario_novo)
        for s in slots_novos:
            if s in slots_ocupados:
                return True # Conflito detectado!
        return False

def montar_grade_sugerida(self, historico, limite_horas=400):
        grade_final = []
        slots_ocupados = []
        total_horas = 0

        # 1. Filtra tudo o que o aluno PODE fazer e que está OFERTADO
        possiveis = []
        for codigo, dados in self.disciplinas.items():
            if not self.checar_equivalencia(codigo, historico): # Se ele ainda não fez
                if self.avaliar_pre_requisitos(dados['Pre_Requisitos'], historico):
                    if dados['Horario'] != 'Não Ofertada':
                        possiveis.append(codigo)

        # 2. Ordena por Aderência Noturna + Importância (Caminho Crítico)
        possiveis = sorted(possiveis, key=lambda c: self.calcular_aderencia_noturna(c), reverse=True)

        # 3. Tenta encaixar na mochila
        for codigo in possiveis:
            dados = self.disciplinas[codigo]

            if total_horas + dados['Credito'] <= limite_horas:
                if not self.tem_conflito(dados['Horario'], slots_ocupados):
                    # Adiciona à grade!
                    grade_final.append(codigo)
                    slots_ocupados.extend(self.extrair_slots(dados['Horario']))
                    total_horas += dados['Credito']

        return grade_final, total_horas
